# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OPcounter_rozm2.ui'
#
# Created: Fri Dec 30 12:45:03 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OpenPalino(object):
    def setupUi(self, OpenPalino):
        OpenPalino.setObjectName(_fromUtf8("OpenPalino"))
        OpenPalino.resize(1199, 775)
        self.centralwidget = QtGui.QWidget(OpenPalino)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(321, 155))
        self.groupBox.setMaximumSize(QtCore.QSize(321, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.inLine = QtGui.QLineEdit(self.groupBox)
        self.inLine.setGeometry(QtCore.QRect(10, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.inLine.setFont(font)
        self.inLine.setText(_fromUtf8(""))
        self.inLine.setObjectName(_fromUtf8("inLine"))
        self.l_keySCuts = QtGui.QLabel(self.groupBox)
        self.l_keySCuts.setGeometry(QtCore.QRect(10, 70, 301, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.l_keySCuts.setFont(font)
        self.l_keySCuts.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_keySCuts.setObjectName(_fromUtf8("l_keySCuts"))
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.APLabel = QtGui.QLabel(self.centralwidget)
        self.APLabel.setMinimumSize(QtCore.QSize(21, 16))
        self.APLabel.setMaximumSize(QtCore.QSize(21, 16))
        self.APLabel.setObjectName(_fromUtf8("APLabel"))
        self.horizontalLayout_3.addWidget(self.APLabel)
        self.uiAPValue = QtGui.QLabel(self.centralwidget)
        self.uiAPValue.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.uiAPValue.setFont(font)
        self.uiAPValue.setObjectName(_fromUtf8("uiAPValue"))
        self.horizontalLayout_3.addWidget(self.uiAPValue)
        self.NAPLabel = QtGui.QLabel(self.centralwidget)
        self.NAPLabel.setMinimumSize(QtCore.QSize(21, 16))
        self.NAPLabel.setMaximumSize(QtCore.QSize(21, 16))
        self.NAPLabel.setObjectName(_fromUtf8("NAPLabel"))
        self.horizontalLayout_3.addWidget(self.NAPLabel)
        self.uiNAPValue = QtGui.QLabel(self.centralwidget)
        self.uiNAPValue.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.uiNAPValue.setFont(font)
        self.uiNAPValue.setObjectName(_fromUtf8("uiNAPValue"))
        self.horizontalLayout_3.addWidget(self.uiNAPValue)
        self.TotalLabel = QtGui.QLabel(self.centralwidget)
        self.TotalLabel.setMinimumSize(QtCore.QSize(31, 16))
        self.TotalLabel.setMaximumSize(QtCore.QSize(31, 16))
        self.TotalLabel.setObjectName(_fromUtf8("TotalLabel"))
        self.horizontalLayout_3.addWidget(self.TotalLabel)
        self.uiTotalValue = QtGui.QLabel(self.centralwidget)
        self.uiTotalValue.setMinimumSize(QtCore.QSize(0, 22))
        self.uiTotalValue.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.uiTotalValue.setFont(font)
        self.uiTotalValue.setObjectName(_fromUtf8("uiTotalValue"))
        self.horizontalLayout_3.addWidget(self.uiTotalValue)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(321, 280))
        self.groupBox_3.setMaximumSize(QtCore.QSize(321, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.b_addTaxa = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(7)
        self.b_addTaxa.setFont(font)
        self.b_addTaxa.setObjectName(_fromUtf8("b_addTaxa"))
        self.horizontalLayout_2.addWidget(self.b_addTaxa)
        self.b_copyTaxa = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(7)
        self.b_copyTaxa.setFont(font)
        self.b_copyTaxa.setObjectName(_fromUtf8("b_copyTaxa"))
        self.horizontalLayout_2.addWidget(self.b_copyTaxa)
        self.b_deleteTaxa = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_deleteTaxa.setFont(font)
        self.b_deleteTaxa.setObjectName(_fromUtf8("b_deleteTaxa"))
        self.horizontalLayout_2.addWidget(self.b_deleteTaxa)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.taxaList = QtGui.QTableWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.taxaList.setFont(font)
        self.taxaList.setAutoScrollMargin(8)
        self.taxaList.setAlternatingRowColors(True)
        self.taxaList.setObjectName(_fromUtf8("taxaList"))
        self.taxaList.setColumnCount(0)
        self.taxaList.setRowCount(0)
        self.taxaList.verticalHeader().setDefaultSectionSize(10)
        self.verticalLayout_3.addWidget(self.taxaList)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(321, 161))
        self.groupBox_2.setMaximumSize(QtCore.QSize(321, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.taxaHist = QtGui.QPlainTextEdit(self.groupBox_2)
        self.taxaHist.setGeometry(QtCore.QRect(10, 20, 301, 131))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.taxaHist.setFont(font)
        self.taxaHist.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.taxaHist.setReadOnly(True)
        self.taxaHist.setTabStopWidth(20)
        self.taxaHist.setObjectName(_fromUtf8("taxaHist"))
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.b_newLayer = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_newLayer.setFont(font)
        self.b_newLayer.setObjectName(_fromUtf8("b_newLayer"))
        self.horizontalLayout.addWidget(self.b_newLayer)
        self.b_delLayer = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_delLayer.setFont(font)
        self.b_delLayer.setObjectName(_fromUtf8("b_delLayer"))
        self.horizontalLayout.addWidget(self.b_delLayer)
        self.b_mergeLayer = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_mergeLayer.setFont(font)
        self.b_mergeLayer.setObjectName(_fromUtf8("b_mergeLayer"))
        self.horizontalLayout.addWidget(self.b_mergeLayer)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.b_newCol = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_newCol.setFont(font)
        self.b_newCol.setObjectName(_fromUtf8("b_newCol"))
        self.horizontalLayout.addWidget(self.b_newCol)
        self.b_delCol = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_delCol.setFont(font)
        self.b_delCol.setObjectName(_fromUtf8("b_delCol"))
        self.horizontalLayout.addWidget(self.b_delCol)
        self.b_mergeCol = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_mergeCol.setFont(font)
        self.b_mergeCol.setObjectName(_fromUtf8("b_mergeCol"))
        self.horizontalLayout.addWidget(self.b_mergeCol)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.b_colWidth = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_colWidth.setFont(font)
        self.b_colWidth.setObjectName(_fromUtf8("b_colWidth"))
        self.horizontalLayout.addWidget(self.b_colWidth)
        self.b_swapRC = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_swapRC.setFont(font)
        self.b_swapRC.setObjectName(_fromUtf8("b_swapRC"))
        self.horizontalLayout.addWidget(self.b_swapRC)
        self.b_numProc = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        self.b_numProc.setFont(font)
        self.b_numProc.setObjectName(_fromUtf8("b_numProc"))
        self.horizontalLayout.addWidget(self.b_numProc)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.mList = QtGui.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.mList.setFont(font)
        self.mList.setAutoScrollMargin(8)
        self.mList.setDragEnabled(False)
        self.mList.setDragDropOverwriteMode(False)
        self.mList.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.mList.setAlternatingRowColors(True)
        self.mList.setObjectName(_fromUtf8("mList"))
        self.mList.setColumnCount(0)
        self.mList.setRowCount(0)
        self.mList.horizontalHeader().setDefaultSectionSize(40)
        self.mList.horizontalHeader().setMinimumSectionSize(20)
        self.verticalLayout_2.addWidget(self.mList)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        OpenPalino.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OpenPalino)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1199, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSorting = QtGui.QMenu(self.menubar)
        self.menuSorting.setObjectName(_fromUtf8("menuSorting"))
        self.menuImport = QtGui.QMenu(self.menubar)
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        OpenPalino.setMenuBar(self.menubar)
        self.actionNew_Project = QtGui.QAction(OpenPalino)
        self.actionNew_Project.setObjectName(_fromUtf8("actionNew_Project"))
        self.actionOpen_Project = QtGui.QAction(OpenPalino)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.actionSave_Project = QtGui.QAction(OpenPalino)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionSave_as_Project = QtGui.QAction(OpenPalino)
        self.actionSave_as_Project.setObjectName(_fromUtf8("actionSave_as_Project"))
        self.actionDirectory = QtGui.QAction(OpenPalino)
        self.actionDirectory.setObjectName(_fromUtf8("actionDirectory"))
        self.actionSave = QtGui.QAction(OpenPalino)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionAutosave_settings = QtGui.QAction(OpenPalino)
        self.actionAutosave_settings.setObjectName(_fromUtf8("actionAutosave_settings"))
        self.actionAlfabetic = QtGui.QAction(OpenPalino)
        self.actionAlfabetic.setCheckable(True)
        self.actionAlfabetic.setObjectName(_fromUtf8("actionAlfabetic"))
        self.actionNumeric = QtGui.QAction(OpenPalino)
        self.actionNumeric.setObjectName(_fromUtf8("actionNumeric"))
        self.actionStratigraphic = QtGui.QAction(OpenPalino)
        self.actionStratigraphic.setObjectName(_fromUtf8("actionStratigraphic"))
        self.actionCreation = QtGui.QAction(OpenPalino)
        self.actionCreation.setCheckable(True)
        self.actionCreation.setChecked(True)
        self.actionCreation.setObjectName(_fromUtf8("actionCreation"))
        self.actionManual = QtGui.QAction(OpenPalino)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.actionA_Z = QtGui.QAction(OpenPalino)
        self.actionA_Z.setCheckable(True)
        self.actionA_Z.setChecked(True)
        self.actionA_Z.setObjectName(_fromUtf8("actionA_Z"))
        self.actionZ_A = QtGui.QAction(OpenPalino)
        self.actionZ_A.setCheckable(True)
        self.actionZ_A.setChecked(False)
        self.actionZ_A.setObjectName(_fromUtf8("actionZ_A"))
        self.actionTaxa_List = QtGui.QAction(OpenPalino)
        self.actionTaxa_List.setObjectName(_fromUtf8("actionTaxa_List"))
        self.actionTable = QtGui.QAction(OpenPalino)
        self.actionTable.setObjectName(_fromUtf8("actionTable"))
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionSave_as_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAutosave_settings)
        self.menuSorting.addAction(self.actionAlfabetic)
        self.menuSorting.addAction(self.actionCreation)
        self.menuSorting.addAction(self.actionManual)
        self.menuSorting.addAction(self.actionNumeric)
        self.menuSorting.addAction(self.actionStratigraphic)
        self.menuSorting.addSeparator()
        self.menuSorting.addAction(self.actionA_Z)
        self.menuSorting.addAction(self.actionZ_A)
        self.menuImport.addAction(self.actionTaxa_List)
        self.menuImport.addAction(self.actionTable)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSorting.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())

        self.retranslateUi(OpenPalino)
        QtCore.QMetaObject.connectSlotsByName(OpenPalino)

    def retranslateUi(self, OpenPalino):
        OpenPalino.setWindowTitle(_translate("OpenPalino", "Open Palino 0.1a", None))
        self.groupBox.setTitle(_translate("OpenPalino", "Counting input", None))
        self.l_keySCuts.setText(_translate("OpenPalino", "aaaa\n"
"bbbb\n"
"cccc\n"
"dddd\n"
"eeee", None))
        self.APLabel.setText(_translate("OpenPalino", "AP:", None))
        self.uiAPValue.setText(_translate("OpenPalino", "---", None))
        self.NAPLabel.setText(_translate("OpenPalino", "NAP:", None))
        self.uiNAPValue.setText(_translate("OpenPalino", "---", None))
        self.TotalLabel.setText(_translate("OpenPalino", "Total:", None))
        self.uiTotalValue.setText(_translate("OpenPalino", "---", None))
        self.groupBox_3.setTitle(_translate("OpenPalino", "Taxa List", None))
        self.b_addTaxa.setText(_translate("OpenPalino", "Add", None))
        self.b_copyTaxa.setText(_translate("OpenPalino", "Duplicate", None))
        self.b_deleteTaxa.setText(_translate("OpenPalino", "Delete", None))
        self.taxaList.setSortingEnabled(True)
        self.groupBox_2.setTitle(_translate("OpenPalino", "History", None))
        self.b_newLayer.setText(_translate("OpenPalino", "New Layer", None))
        self.b_delLayer.setText(_translate("OpenPalino", "Delete Layer", None))
        self.b_mergeLayer.setText(_translate("OpenPalino", "Merge Layers", None))
        self.b_newCol.setText(_translate("OpenPalino", "New Column", None))
        self.b_delCol.setText(_translate("OpenPalino", "Delete Column", None))
        self.b_mergeCol.setText(_translate("OpenPalino", "Merge Columns", None))
        self.b_colWidth.setText(_translate("OpenPalino", "5/10/all", None))
        self.b_swapRC.setText(_translate("OpenPalino", "Swap R/C", None))
        self.b_numProc.setText(_translate("OpenPalino", "Num / %", None))
        self.menuFile.setTitle(_translate("OpenPalino", "File", None))
        self.menuSorting.setTitle(_translate("OpenPalino", "Sorting", None))
        self.menuImport.setTitle(_translate("OpenPalino", "Import", None))
        self.actionNew_Project.setText(_translate("OpenPalino", "New Project", None))
        self.actionOpen_Project.setText(_translate("OpenPalino", "Open Project", None))
        self.actionSave_Project.setText(_translate("OpenPalino", "Save Project", None))
        self.actionSave_as_Project.setText(_translate("OpenPalino", "Save Project As", None))
        self.actionDirectory.setText(_translate("OpenPalino", "Directory", None))
        self.actionSave.setText(_translate("OpenPalino", "Save", None))
        self.actionAutosave_settings.setText(_translate("OpenPalino", "Autosave settings", None))
        self.actionAlfabetic.setText(_translate("OpenPalino", "Alfabetic", None))
        self.actionNumeric.setText(_translate("OpenPalino", "Numeric", None))
        self.actionStratigraphic.setText(_translate("OpenPalino", "Stratigraphic", None))
        self.actionCreation.setText(_translate("OpenPalino", "Creation", None))
        self.actionManual.setText(_translate("OpenPalino", "Manual", None))
        self.actionA_Z.setText(_translate("OpenPalino", "A...Z", None))
        self.actionZ_A.setText(_translate("OpenPalino", "Z...A", None))
        self.actionTaxa_List.setText(_translate("OpenPalino", "Taxa List", None))
        self.actionTable.setText(_translate("OpenPalino", "Table", None))

